services:
  - type: web
    name: bridge-server
    env: node
    rootDir: server
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: CLIENT_ORIGIN
        sync: false
  - type: web
    name: bridge-web
    env: static
    rootDir: web
    buildCommand: npm ci && npm run build
    staticPublishPath: build
    envVars:
      - key: REACT_APP_API_URL
        value: https://bridge-twoz.onrender.com
